"""Weekly digest: what you saved, the themes across it, what to read first, and how it connects
to your focus areas. Generated by Claude (or a plain grouped list without an AI key), saved as
Markdown under /data/digests and emailed. Runs on a schedule and on demand."""
import datetime as dt
import html
import json
import logging
import re
import smtplib
import threading
import time
from collections import Counter
from email.message import EmailMessage
from pathlib import Path

from . import config, db, mailer

log = logging.getLogger("vault.digest")

PROMPT = """You are writing a personal weekly research digest for a senior RAN / O-RAN / 5G engineer who is
moving into RAN AI engineering and research. Their focus areas: {interests}.

Below are the items they saved from LinkedIn in the last {days} days (id, date, title, author, tags,
summary or text excerpt, attached documents/papers/videos). Write the digest in Markdown:

## This week in one paragraph
## Themes
(3-5 themes; for each: 1-2 sentences and the item ids like [#12])
## Read first
(the 3 most valuable items for their goals, why, and roughly how long it takes — prefer papers/white papers)
## Connections to your work
(concrete links to their focus areas; ideas they could try in a lab, rApp/xApp or paper)
## Worth a follow-up
(open questions, specs or papers to look up next)

Rules: cite items as [#id]; only use the items below; be concise and specific; no filler.

ITEMS:
{items}"""


def _items(days: int) -> list:
    since = time.time() - 86400 * days
    out = []
    for r in db.recent(2000):
        if r["created_at"] < since or r["status"] not in ("done", "link_only"):
            continue
        m = {}
        f = Path(r["folder"] or "") / "meta.json"
        if f.exists():
            try:
                m = json.loads(f.read_text(encoding="utf-8"))
            except Exception:
                m = {}
        out.append({"id": r["id"], "date": dt.datetime.fromtimestamp(r["created_at"]).strftime("%Y-%m-%d"),
                    "title": r["title"] or m.get("title") or r["url"], "author": r["author"] or m.get("author", ""),
                    "url": r["url"] or m.get("url"), "tags": m.get("tags") or [t for t in (r["tags"] or "").split(",") if t],
                    "summary": m.get("summary") or "", "text": (m.get("text") or "")[:700],
                    "document": (m.get("document") or {}).get("title"),
                    "papers": [p.get("title") or p.get("id") for p in m.get("papers") or []],
                    "video": bool(m.get("videos")), "youtube": [y.get("title") for y in m.get("youtube") or []]})
    return sorted(out, key=lambda x: x["id"])


def _plain(items: list, days: int) -> str:
    """Digest without AI: counts + items grouped by their top tag."""
    tags = Counter(t for it in items for t in it["tags"])
    lines = [f"## {len(items)} items saved in the last {days} days", "",
             "**Top topics:** " + ", ".join(f"{t} ({n})" for t, n in tags.most_common(8)), ""]
    groups = {}
    for it in items:
        groups.setdefault(it["tags"][0] if it["tags"] else "other", []).append(it)
    for tag, its in sorted(groups.items(), key=lambda kv: -len(kv[1])):
        lines.append(f"## {tag}")
        lines += [f"- [#{it['id']}] {it['title'][:110]} — {it['author']}" for it in its]
        lines.append("")
    lines.append("_Add ANTHROPIC_API_KEY to .env for themes, reading priorities and connections to your work._")
    return "\n".join(lines)


def _ai(items: list, days: int) -> str:
    import anthropic
    blob = "\n\n".join(
        f"[#{it['id']}] {it['date']} — {it['title']}\nAuthor: {it['author']}\nTags: {', '.join(it['tags'])}\n"
        + (f"Summary: {it['summary']}\n" if it["summary"] else f"Text: {it['text']}\n")
        + (f"Document: {it['document']}\n" if it["document"] else "")
        + (f"Papers: {'; '.join(it['papers'])}\n" if it["papers"] else "")
        + ("Has a saved video\n" if it["video"] else "")
        + (f"YouTube: {'; '.join(it['youtube'])}\n" if it["youtube"] else "")
        for it in items)[:150000]
    resp = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY).messages.create(
        model=config.CLAUDE_MODEL, max_tokens=3000,
        messages=[{"role": "user", "content": PROMPT.format(interests=config.INTERESTS, days=days, items=blob)}])
    return "".join(b.text for b in resp.content if getattr(b, "type", "") == "text").strip()


def md_to_html(md: str, base_url: str = "") -> str:
    """Tiny Markdown → HTML for emails and the dashboard (headings, bullets, bold, links, [#id])."""
    out, in_list = [], False
    for line in md.splitlines():
        esc = html.escape(line)
        esc = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", esc)
        esc = re.sub(r"(?<!\*)\*(?!\*)(.+?)\*", r"<i>\1</i>", esc)
        esc = re.sub(r"^_(.+)_$", r"<i>\1</i>", esc)
        esc = re.sub(r"\[([^\]]+)\]\((https?://[^)]+)\)", r'<a href="\2">\1</a>', esc)
        esc = re.sub(r"\[#(\d+)\]", rf'<a class="cite" data-id="\1" href="{base_url}/dashboard#item-\1">[#\1]</a>', esc)
        if re.match(r"^\s*[-*] ", line):
            if not in_list:
                out.append("<ul>"); in_list = True
            out.append("<li>" + re.sub(r"^\s*[-*] ", "", esc) + "</li>")
            continue
        if in_list:
            out.append("</ul>"); in_list = False
        m = re.match(r"^(#{1,4}) (.*)", esc)
        if m:
            n = len(m.group(1)) + 1
            out.append(f"<h{n}>{m.group(2)}</h{n}>")
        elif esc.strip():
            out.append(f"<p>{esc}</p>")
    if in_list:
        out.append("</ul>")
    return "\n".join(out)


def build(days: int = None, send: bool = True) -> dict:
    days = days or config.DIGEST_DAYS
    items = _items(days)
    today = dt.date.today()
    title = f"Vault digest — {len(items)} saves, week of {(today - dt.timedelta(days=days - 1)):%b %d}–{today:%b %d, %Y}"
    if not items:
        body = f"Nothing was saved in the last {days} days."
    else:
        try:
            body = _ai(items, days) if config.ANTHROPIC_API_KEY else _plain(items, days)
        except Exception as e:
            log.warning("AI digest failed (%s); sending the plain version", e)
            body = _plain(items, days)
    md = f"# {title}\n\n{body}\n"
    config.DIGESTS_DIR.mkdir(parents=True, exist_ok=True)
    name = f"{today:%Y-%m-%d}_{days}d.md"
    (config.DIGESTS_DIR / name).write_text(md, encoding="utf-8")
    sent = False
    if send and items and mailer.enabled():
        try:
            _email(title, md)
            sent = True
        except Exception as e:
            log.warning("digest email failed: %s", e)
    log.info("digest %s: %s items, emailed=%s", name, len(items), sent)
    return {"name": name, "title": title, "items": len(items), "emailed": sent, "markdown": md}


def _email(title: str, md: str) -> None:
    msg = EmailMessage()
    msg["Subject"] = f"[Vault digest] {title.replace('Vault digest — ', '')}"
    msg["From"], msg["To"] = config.SMTP_USER, config.MAIL_TO
    msg.set_content(md)
    msg.add_alternative(f"<div style='font-family:Arial,sans-serif;max-width:760px;line-height:1.45'>{md_to_html(md, config.PUBLIC_URL)}</div>",
                        subtype="html")
    with smtplib.SMTP(config.SMTP_HOST, config.SMTP_PORT, timeout=60) as s:
        s.starttls()
        s.login(config.SMTP_USER, config.SMTP_PASSWORD)
        s.send_message(msg)


def list_digests() -> list:
    if not config.DIGESTS_DIR.exists():
        return []
    out = []
    for f in sorted(config.DIGESTS_DIR.glob("*.md"), reverse=True):
        first = f.read_text(encoding="utf-8").splitlines()[0].lstrip("# ").strip()
        out.append({"name": f.name, "title": first})
    return out


def read_digest(name: str) -> dict:
    f = config.DIGESTS_DIR / Path(name).name
    if not f.exists():
        return {}
    md = f.read_text(encoding="utf-8")
    return {"name": f.name, "markdown": md, "html": md_to_html(md)}


def _scheduler(stop: threading.Event) -> None:
    """Checks every 10 minutes; sends once per ISO week at DIGEST_WEEKDAY / DIGEST_HOUR (local time)."""
    while not stop.wait(600):
        try:
            now = dt.datetime.now()
            week = f"{now.isocalendar()[0]}-W{now.isocalendar()[1]:02d}"
            if (now.weekday() == config.DIGEST_WEEKDAY and now.hour >= config.DIGEST_HOUR
                    and db.get_setting("digest_last_week") != week):
                build()
                db.set_setting("digest_last_week", week)
        except Exception as e:
            log.warning("digest scheduler: %s", e)


def start(stop: threading.Event) -> None:
    if config.DIGEST_ENABLED:
        threading.Thread(target=_scheduler, args=(stop,), daemon=True, name="digest").start()
        log.info("weekly digest on: weekday %s at %s:00", config.DIGEST_WEEKDAY, config.DIGEST_HOUR)
